[tool.poetry]
name = "onfido-score-analysis"
version = "0.2.0"
description = "Code to evaluate models"
authors = [
    "Martins Bruveris <martins.bruveris@onfido.com>",
]
readme = "README.md"
packages = [{include = "score_analysis"}]

[[tool.poetry.source]]
name = "onfido"
url = "https://nexus.mgmt.onfido.xyz/repository/pypi/simple"
priority = "default"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "*"
pandas = "*"
scipy = "*"

# Documentation
enum-tools = { version = "*", optional = true }
sphinx = { version = "^4.4.0", optional = true }
sphinx-rtd-theme = { version = "*", optional = true }
sphinx-toolbox = { version = "^2.0.0", optional = true }

# Jupyter
jupyter = { version = "*", optional = true }
matplotlib = { version = "*", optional = true }
seaborn = { version = "*", optional = true }
tqdm = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
bumpversion = "*"
flake8 = "*"
isort = "*"
pre-commit = "*"
pytest = "*"
pytest-black = "*"
pytest-cov = "*"
pytest-flake8 = "*"
pytest-isort = "*"
pytest-xdist = "*"
taskipy = "*"

[tool.poetry.extras]
# To compile documentation
docs = ["enum-tools", "sphinx", "sphinx-rtd-theme", "sphinx-toolbox"]
# To work with jupyter notebooks
jupyter = ["jupyter", "matplotlib", "seaborn", "tqdm"]

[tool.taskipy.tasks]
bumpversion = "poetry run bumpversion patch && git push && git push --tags"
docs-build = "sphinx-build docs docs/_build/html"
docs-server = "sphinx-autobuild docs docs/_build/html --open-browser --watch=onfido_pipelines/"

[tool.black]
line-length = 88
include = "\\.pyi?$"
exclude = """
/(
    \\.git
  | \\.tox
  | \\.venv
  | tmp
)/
"""

[tool.isort]
profile = "black"

[tool.coverage.run]
omit = ["score_analysis/experimental/*"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
